# Generated by Django 4.2.1 on 2023-06-14 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='product_1', max_length=30),
        ),
    ]
