# Generated by Django 4.2.1 on 2023-06-13 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_student_id_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='credit',
            new_name='mark',
        ),
    ]
